@port = 8000
@baseUrl = http://127.0.0.1:{{port}}

### get info
GET {{baseUrl}} HTTP/1.1


#### create database structure 
POST {{baseUrl}}/create-structure-database HTTP/1.1
Content-Type: application/json

{
    "name":"CTM_SCRIPT_01"
}

### 
POST {{baseUrl}}/structure-media HTTP/1.1
Content-Type: application/json

{
    "name":"ctm-python-script"
}

### insert database information basic
POST {{baseUrl}}/insert-data-database HTTP/1.1
Content-Type: application/json

{
    "name":"CTM_SCRIPT_01"
}





